"""empty message

Revision ID: c5eea8d48424
Revises: d71fa1251dfe
Create Date: 2024-04-06 11:40:33.551471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5eea8d48424'
down_revision = 'd71fa1251dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_menu', 't_menu', ['pid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_menu', type_='foreignkey')
    # ### end Alembic commands ###
